podTemplate(yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dotnet
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command:
    - cat
    tty: true

  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - /busybox/cat
    tty: true
""") {

    node(POD_LABEL) {

        stage('Restore') {
            container('dotnet') {
                sh 'dotnet restore WebApplication1/WebApplication1.csproj'
            }
        }

        stage('Build') {
            container('dotnet') {
                sh 'dotnet build WebApplication1/WebApplication1.csproj --configuration Release'
            }
        }

        stage('Publish') {
            container('dotnet') {
                sh 'dotnet publish WebApplication1/WebApplication1.csproj -c Release -o publish'
            }
        }

    }
}