pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:8.0'
          }
	}

	

    stages {

        stage('Checkout Source') {
            steps {
                git branch: 'main',
                credentialsId: 'github-creds',
                url: 'https://github.com/mohamedzaid111/MyTestRepo001.git'
            }
        }

	 stage('Restore') {
            steps {
		sh "dotnet restore WebApplication1/WebApplication1.csproj" 
            }
        }

	 stage('Build') {
            steps {
		sh "dotnet build 'WebApplication1/WebApplication1.csproj --no-restore"
            }
        }


    }

    post {

        success {
            echo 'CI Pipeline completed successfully'
        }

        failure {
            echo 'Pipeline failed'
        }

        always {
            echo 'Pipeline execution done..'
        }
    }
}