pipeline {
    agent any

    stages {

        stage('Checkout Source') {
            steps {
                git branch: 'main',
                credentialsId: 'github-creds',
                url: 'https://github.com/mohamedzaid111/MyTestRepo001.git'
            }
        }


        stage('Build') {
          steps {
          bat 'dir /s /b *.sln'

             dir('WebApplication1') {
               bat 'dotnet restore'
               bat 'dotnet build --configuration Release'
          }
    }
   }

       stage('Run Unit Tests') {
          steps {
          bat 'dir /s /b *.sln'

            dir('WebApplication1') {
            bat 'dotnet test --configuration Release --no-build'
        }
    }
   }


    }
}